# Generated by Django 4.2.20 on 2025-08-14 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paginasweb", "0002_alter_status_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aluno",
            options={"ordering": ["nome", "matricula"]},
        ),
        migrations.AlterModelOptions(
            name="campus",
            options={"ordering": ["nome"]},
        ),
        migrations.AlterModelOptions(
            name="curso",
            options={"ordering": ["nome", "campus"]},
        ),
        migrations.AlterModelOptions(
            name="historico",
            options={"ordering": ["-cadastrado_em"]},
        ),
        migrations.AlterModelOptions(
            name="servidor",
            options={"ordering": ["nome", "siape"]},
        ),
        migrations.AlterModelOptions(
            name="solicitacao",
            options={"ordering": ["-cadastrado_em"]},
        ),
        migrations.AlterModelOptions(
            name="tiposolicitacao",
            options={"ordering": ["descricao"]},
        ),
        migrations.RenameField(
            model_name="aluno",
            old_name="matrícula",
            new_name="matricula",
        ),
    ]
